make: main.cpp Socket_server.cpp Socket_threading.cpp
	g++ -std=c++11 -pthread -o server main.cpp Socket_server.cpp Socket_server.h Socket_threading.h Socket_threading.cpp Json_conversion.h Json_conversion.cpp Chair.cpp Chair.h -ljsoncpp
