make: main.cpp
	g++ -std=c++11 -o server main.cpp Socket.cpp Socket.h \
	Components/Base/Component.h Components/Base/Component.cpp \
	Components/Base/WithLed.h \
	Components/Base/WithLed.cpp Components/Base/WithForceSensor.h \
	Components/Base/WithForceSensor.cpp Components/Bed.h \
	Components/Bed.cpp \
	Components/Door.cpp Components/Door.h \
	Components/Chair.h Components/Chair.cpp \
	Components/TableLamp.cpp Components/TableLamp.h \
	Json_conversion.h Json_conversion.cpp -ljsoncpp
